config/routes.rb
Railsgirls::Application.routes.draw do
  get "pages/info"
  get "pages/penis"
  
  resources :ideas

  root 'pages#info'
  

  

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :discription, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
  
  def penis
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_area :discription %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1 class="hallo" >Schreib hier mal ne krasse Idee hin!</h1>

<table class>
  <thead>
    <tr>
      <th>Name</th>
      <th>Discription</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.discription %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @idea.discription %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width => 150) if @idea.picture.present? %>
  
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RUBY ROCKS!</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Johannes on Rails ROCKS!</a>
      <ul class="nav">
        <li class="active"><a href="/ideas">Ideas</a></li>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
    </div>
  </div>
</div>
<div class="container stuff">
  <% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
<%= yield %>
</div>

</body>
<footer>
  <div class="container hallo">
    Johannes in Nairobaay!
  </div>
</footer>
</html>

app/views/pages/info.html.erb
<h1>Johannes rocks ruby HARD!</h1>
<p>Bryanne goes to havannah on thursday rather than helping orphans with me!! :) .</p>
<br>
<%=link_to "Krasse Ideen", ideas_path%> <br>
<br>
<a href ="/ideas" target="_blank">go to a new page<a/>
<br>
<%=link_to "neue Seite", pages_penis_path%>

app/views/pages/johannes.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Johannes on Ruby Rocks!!</title>
</head>
<body>
	bryanne marry me!!! 50$!!!\
	
	
	<div style= "color: purple; width:500px; height:300px; background-color: pistaccio">
		Paul marry me!!! 50$!!!

	</div>
	<div>
		tina marry me!!! 50$!!!\

	</div>
</body>
</html>

app/views/pages/penis.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Johannes on Ruby Rocks!!</title>

	<style type="text/css" media="screen">
/*
	color: blue; 
	width:35%; height:100px; 
	background-color: yellow
	*/

	table#lucky
	{
		border: 5px 
		solid blue; 
		width=500px; 
		height: 300px
	}


	</style>
</head>
<body>

<div> 
	
	<div style= "color: purple; width:35%; height:100px; background-color: green; display:inline">
		Paul marry me!!! 50$!!!

	</div>	
	<div style= "color: blue; width:35%; height:100px; background-color: red; display:inline">
		tina marry me!!! 50$!!! 
	</div>


		<br/>

		<img class="scaledImageFitWidth img" src="https://fbcdn-sphotos-d-a.akamaihd.net/hphotos-ak-frc3/p480x480/1457721_10201889564033767_748559615_n.jpg" style="top:-84px; width:200px; 	height:250px" alt="Photo: Ach Jay... Du fehlst! &lt;3">
		<br/>

		<img class="coverPhotoImg photo img" src="https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-ash2/c0.113.851.315/p851x315/857211_10151836717913018_230878651_o.jpg" alt="Cover Photo" style="top:0px;width:79%" data-fbid="10151836717913018">

		<img src="hallo.jpg" alt="good practice">
	<br/>

	<table id="lucky">

		<caption>COOL WORDS TABLE!!</caption>
		<thead>
			<tr>
				<th>SWHAELI</th>
				<th>german</th>
				<th>english</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>ina choma </td> 
				<td>stiker </td>
				<td>bryanne </td>
			</tr>
			<tr>
				<td>data 1</td>
				<td>data 2</td>
				<td>data 3</td>
			</tr>
		</tbody>
	</table>
	</div>
</div>
</body>
</html>